version: '3'

services:
  javaapp:
    image: dhl-alpine-tomcat-java-app/dhl-java-rest
    ports:
      - 8084:8080
    networks:
      - isolated
  mysqlapp:
    image: dhl-alpine-tomcat-java-app/dhl-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret 
    ports:
      - 3311:3306
    networks:
      - isolated

networks: 
  isolated:
    driver: bridge
