version: '3'

services:
  javaapp:
    image: mixaverross88/dockerize_java_mysql_example_project:prod
    ports:
      - 80:8080
    networks:
      - isolated
    volumes:
      - /$(pwd):/usr/local/tomcat/webapps
  mysqlapp:
    image: mixaverross88/dockerize_java_mysql_example_project:mysql_prod
    secrets:
      - mysql_root_pass
    enviroment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_pass
    ports:
      - 3306:3306
    networks:
      - isolated
    volumes:
      - /$(pwd):/usr/local/tomcat/webapps

volumes:
  isolated:
    external: false
secrets:
  mysql_root_pass:
    external: true
